### ISSUE TITLE
想要咨询大佬一个问题，不确定是代码导致的还是寻路的问题。兑换图拉尔票据时会卡在收藏品柜台吗？

### ISSUE THREAD

**Issue by OberFlag** [Bread-Sp/Fate-Farming-CN-Client-#1]
想要咨询大佬一个问题，不确定是代码导致的还是寻路的问题。兑换图拉尔票据时会卡在收藏品柜台吗？

**Comment by Bread-Sp** [comment]
描述的再具体一点，是卡在npc前不会自动点npc兑换吗还是一直重复对话
如果是重复对话的话代表你的fate完成度不够还不能兑换，需要在设置里关闭自动兑换去手动兑换成其他东西或任由其溢出。
不过这几天在外面旅游没带笔记本暂时修不了bug，需要等七号回家后才能修

**Comment by OberFlag** [comment]
> 描述的再具体一点，是卡在npc前不会自动点npc兑换吗还是一直重复对话 如果是重复对话的话代表你的fate完成度不够还不能兑换，需要在设置里关闭自动兑换去手动兑换成其他东西或任由其溢出。 不过这几天在外面旅游没带笔记本暂时修不了bug，需要等七号回家后才能修

感谢大佬深夜答复，刚才复现了下，卡在第九解决方案的X8.6 Y14.0，NPC柯特克的柜台那里。被柜台挡住了路一直在对着柜台跑。明天我重新用寻路插件构建一遍第九解决方案的地图再看看。

**Comment by OberFlag** [comment]
大佬好，重新构建地图后。我试着自己用vanvmash设定了脚本里的目标点跑了一遍测试正常，目前测试也都正常。这个issues可以关了~
