### ISSUE TITLE
大佬知不知道Something Need Doing这几个额外仓库插件安装失败是什么原因啊？

### ISSUE THREAD

**Issue by EmiyaTakaya** [Bread-Sp/Fate-Farming-CN-Client-#2]
测试那边添加repo安装失败，又尝试网上添加本地插件的方法也还是安装不了，梯子开全局了都。
![QQ20241129-041428](https://github.com/user-attachments/assets/1bb92b0b-f679-4654-ba68-9cd3f0841ea9)
![QQ20241129-041500](https://github.com/user-attachments/assets/029d3458-b4a1-4d90-b032-8f179a965893)

**Comment by Bread-Sp** [comment]
repo安装的版本是国际服的版本，我也没找到能直接使用的库，本地的话你需要在snd的github找国际服7.05的版本下载使用

**Comment by EmiyaTakaya** [comment]
![QQ20241130-024917](https://github.com/user-attachments/assets/24fb3be0-a309-4e18-9a61-d6c8cc60e0cd)
是在这下旧版本吗？这边只看到源代码。

**Comment by Bread-Sp** [comment]
给个邮箱我可以发一份给你

**Comment by EmiyaTakaya** [comment]
感谢！emiyatakaya@gmail.com

**Comment by EmiyaTakaya** [comment]
![QQ20241201-225729](https://github.com/user-attachments/assets/ed95a26e-fd15-4dd9-84b7-4c01f6cc2f35)
呜呜

**Comment by Bu-Chen** [comment]
大佬您好，7.05的sndex可以发给我一份嘛，我尝试编译国际服7.05的源代码，太菜了编译不出来orz
我的邮箱ytygogogo@gmail.com
万分感谢！

> 给个邮箱我可以发一份给你

**Comment by Bread-Sp** [comment]
> ![QQ20241201-225729](https://private-user-images.githubusercontent.com/80833862/391341121-ed95a26e-fd15-4dd9-84b7-4c01f6cc2f35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMDYwMzIsIm5iZiI6MTczMzIwNTczMiwicGF0aCI6Ii84MDgzMzg2Mi8zOTEzNDExMjEtZWQ5NWEyNmUtZmQxNS00ZGQ5LTg0YjctNGMwMWY2Y2MyZjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDA2MDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZGY1MjBkNTQzNGFmODYxODVhMjQ0NjIwN2ViYzBiZGY0NDMxOTIzOTdlNmI1MzZiMzdhNmMxMzc5MmY2ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3PMhaEvdnxYYx1V1bpWftFNu1I5a4BxtXW5JUA9G46M) 呜呜
权限更新了，再打开哪个网址就可以了

**Comment by Bread-Sp** [comment]
> ![QQ20241201-225729](https://private-user-images.githubusercontent.com/80833862/391341121-ed95a26e-fd15-4dd9-84b7-4c01f6cc2f35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMDYwMzIsIm5iZiI6MTczMzIwNTczMiwicGF0aCI6Ii84MDgzMzg2Mi8zOTEzNDExMjEtZWQ5NWEyNmUtZmQxNS00ZGQ5LTg0YjctNGMwMWY2Y2MyZjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDA2MDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZGY1MjBkNTQzNGFmODYxODVhMjQ0NjIwN2ViYzBiZGY0NDMxOTIzOTdlNmI1MzZiMzdhNmMxMzc5MmY2ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3PMhaEvdnxYYx1V1bpWftFNu1I5a4BxtXW5JUA9G46M) 呜呜

权限更新了，再打开那个网址就可以了

**Comment by Bread-Sp** [comment]
> 大佬您好，7.05的sndex可以发给我一份嘛，我尝试编译国际服7.05的源代码，太菜了编译不出来orz 我的邮箱[ytygogogo@gmail.com](mailto:ytygogogo@gmail.com) 万分感谢！
> 
> > 给个邮箱我可以发一份给你

https://drive.google.com/file/d/1V0CRwdbM1_V2SgiKH6qcEZQmD4NFJlPD/view?usp=drive_link

**Comment by EmiyaTakaya** [comment]
请问BossmodReborn是使用哪个版本啊？作者更新太多了，试到7.0.1.0都不能用...

**Comment by EmiyaTakaya** [comment]
![QQ20241204-145626](https://github.com/user-attachments/assets/20ff0e25-3839-46d0-b1ab-17c380b7d6ed)
自动寻路是被ban了吗，昨天还能用啊。

**Comment by Bread-Sp** [comment]
> ![QQ20241204-145626](https://private-user-images.githubusercontent.com/80833862/392260199-20ff0e25-3839-46d0-b1ab-17c380b7d6ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMjg2MTUsIm5iZiI6MTczNDAyODMxNSwicGF0aCI6Ii84MDgzMzg2Mi8zOTIyNjAxOTktMjBmZjBlMjUtMzgzOS00NmQwLWIxYWItMTdjMzgwYjdkNmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDE4MzE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NDkwNjg1N2JmODExNjhjZDQ1NDBiYTI5MGNhZTI3ZTE3ZWZmOWE0MWRiNGI5ZjFiZmQ5ZGRjNTBiNjY5MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sw1ekmO9bQrA_y4ELqSHq25BCm5FmjrFdaajwMCrqFQ) 自动寻路被禁止了吗，昨天还能用啊。

逆光库内的线上Dont Ban My Plugin

**Comment by EmiyaTakaya** [comment]
已经解决啦，最开始弄的时候搞了个uban，后面就没考虑过反ban的问题，换了don't这个就好了。

**Comment by Bread-Sp** [comment]
> 测试那边添加repo安装失败，又尝试网上添加本地插件的方法也还是安装不了，梯子开全局了都。 ![QQ20241129-041428](https://private-user-images.githubusercontent.com/80833862/390898765-1bb92b0b-f679-4654-ba68-9cd3f0841ea9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2Nzk4NjEsIm5iZiI6MTczNTY3OTU2MSwicGF0aCI6Ii84MDgzMzg2Mi8zOTA4OTg3NjUtMWJiOTJiMGItZjY3OS00NjU0LWJhNjgtOWNkM2YwODQxZWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDIxMTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZTkzMjVhOGNjN2ZlY2QwNDQxMmZhMjY4MzhiZmJkMmVhYmNhMmU1YmZjZTI4MDRhOWM1NTllM2ZmODI4MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TGgMWWkT-To5WM4PboAhRLo22tYdpVG32rlypODN0bo) ![QQ20241129-041500](https://private-user-images.githubusercontent.com/80833862/390898774-029d3458-b4a1-4d90-b032-8f179a965893.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2Nzk4NjEsIm5iZiI6MTczNTY3OTU2MSwicGF0aCI6Ii84MDgzMzg2Mi8zOTA4OTg3NzQtMDI5ZDM0NTgtYjRhMS00ZDkwLWIwMzItOGYxNzlhOTY1ODkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDIxMTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NzQ0MDg0N2RmYjI2NGI1OTczZTEwMjZiOGZlNzAxYzY1ODJkNWU3MmExOGE1YjQyYWVjMWY2Nzg5ZWFlYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IXFc_T3IS-xUlXq7g0pKxxHgji9W7VyXYNK40NyNm10)
